# Global Settings
timezone: America/New_York

# Site settings
title: samuelchampagne.com
description: "A male human of 19 earthly rotations // Frontend Web Developer"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://samuelchampagne.com" # the base hostname & protocol for your site
twitter_username: myhonor16
github_username:  myhonor16

permalink: /:year/:month/:title/
paginate: 6
paginate_path: "archive/:num/"

# Build settings
markdown: kramdown

sass:
  style: :compressed

# Serve Settings
port: 9000

